# Generated by Django 2.2.5 on 2019-09-05 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190905_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='D_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Department'),
        ),
        migrations.AlterField(
            model_name='city',
            name='S_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.State'),
        ),
    ]
